version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: mydatabase
      #MYSQL_USER: myuser
      #MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    volumes:
      - /data:/data/redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]